name: base58
version: git
summary: Base58 and Base58Check implementation
description: |
  Base58 and Base58Check implementation compatible with what is used by the
  bitcoin network.

grade: stable
confinement: strict

apps:
  base58:
    command: base58

parts:
  base58:
    source: .
    plugin: python
